# Generated by Django 2.0 on 2018-10-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allotted', models.PositiveIntegerField(default=None)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
