# Generated by Django 2.0 on 2018-10-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='allotted',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
