# Generated by Django 2.0 on 2018-10-28 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_center_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
