# Generated by Django 2.0 on 2018-10-29 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_center_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_point', models.CharField(max_length=200)),
                ('allotment', models.PositiveIntegerField(default=None, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
