# Generated by Django 2.0 on 2018-11-03 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_distribution_center_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
