# Generated by Django 2.0 on 2018-12-02 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181103_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='chennai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('t_id', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='mumbai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('t_id', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
