# Generated by Django 2.0 on 2018-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chennai_mumbai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennai',
            name='imei',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
