# Generated by Django 2.0 on 2018-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181202_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennai',
            name='t_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
