# Generated by Django 2.0 on 2018-12-02 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181202_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennai',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
