# Generated by Django 2.0 on 2018-12-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181202_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mumbai',
        ),
    ]
