# Generated by Django 2.0 on 2018-12-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_chennai_center_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
