# Generated by Django 2.0 on 2018-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_center_center_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='distribution_point',
            new_name='imei',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='allotment',
            new_name='tablet_id',
        ),
        migrations.AddField(
            model_name='distribution',
            name='allotted_to',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
