# Generated by Django 2.0 on 2018-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181202_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
