# Generated by Django 2.0 on 2018-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_distribution_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
