# Generated by Django 2.0 on 2018-12-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_center_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='condition',
        ),
        migrations.AddField(
            model_name='distribution',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
