# Generated by Django 2.0 on 2018-12-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_chennai_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='chennai',
            name='at',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
