# Generated by Django 2.0 on 2018-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_chennai_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='at',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
