# Generated by Django 2.0 on 2018-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_distribution_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chennai',
            name='receive_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
